AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EcrTrain:
    Type: String
  EcrPredict:
    Type: String

Resources:
  TrainPipelineRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrTrain

  PredictPipelineRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrPredict
