AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ECR_Train:
    Type: String
  ECR_Predict:
    Type: String

Resources:
  TrainPipelineRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECR_Train

  PredictPipelineRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECR_Predict
