AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TrainPipelineRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECR_Train

  PredictPipelineRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECR_Predict
