AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TrainPipelineRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: train-pipeline

  PredictPipelineRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: predict-pipeline
