AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TrainLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/train-pipeline
      RetentionInDays: 7

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsTaskExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TrainPipelineTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: train-pipeline-task
      Cpu: '512'  # 0.5 vCPU
      Memory: '1024'  # 1 GB RAM
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      ContainerDefinitions:
        - Name: train-pipeline
          Image: 831926591468.dkr.ecr.eu-central-1.amazonaws.com/train-pipeline:latest
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/train-pipeline
              awslogs-region: eu-central-1
              awslogs-stream-prefix: ecs
