AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TrainLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/train-pipeline
      RetentionInDays: 7
  PredictLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/predict-pipeline
      RetentionInDays: 7

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsTaskExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: AllowReadSecretsManager
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - arn:aws:secretsmanager:eu-central-1:831926591468:secret:mlops0/csv_filename-RIH01d
                  - arn:aws:secretsmanager:eu-central-1:831926591468:secret:mlops0/csv_url-hPpliW
                  - arn:aws:secretsmanager:eu-central-1:831926591468:secret:mlops0/s3_bucket_name-cAiL75
        - PolicyName: AllowS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::athos-mlops0-bucket/*

  TrainPipelineTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: train-pipeline-task
      Cpu: '512'  # 0.5 vCPU
      Memory: '1024'  # 1 GB RAM
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt ExecutionRole.Arn
      ContainerDefinitions:
        - Name: train-pipeline
          Image: 831926591468.dkr.ecr.eu-central-1.amazonaws.com/train-pipeline:latest
          Essential: true
          Secrets:
            - Name: CSV_URL
              ValueFrom: arn:aws:secretsmanager:eu-central-1:831926591468:secret:mlops0/csv_url-hPpliW
            - Name: CSV_FILENAME
              ValueFrom: arn:aws:secretsmanager:eu-central-1:831926591468:secret:mlops0/csv_filename-RIH01d
            - Name: S3_BUCKET_NAME
              ValueFrom: arn:aws:secretsmanager:eu-central-1:831926591468:secret:mlops0/s3_bucket_name-cAiL75
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/train-pipeline
              awslogs-region: eu-central-1
              awslogs-stream-prefix: ecs

  PredictPipelineTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: predict-pipeline-task
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt ExecutionRole.Arn
      ContainerDefinitions:
        - Name: predict-pipeline
          Image: 831926591468.dkr.ecr.eu-central-1.amazonaws.com/predict-pipeline:latest
          Essential: true
          Secrets:
            - Name: CSV_FILENAME
              ValueFrom: arn:aws:secretsmanager:eu-central-1:831926591468:secret:mlops0/csv_filename-RIH01d
            - Name: CSV_URL
              ValueFrom: arn:aws:secretsmanager:eu-central-1:831926591468:secret:mlops0/csv_url-hPpliW
            - Name: S3_BUCKET_NAME
              ValueFrom: arn:aws:secretsmanager:eu-central-1:831926591468:secret:mlops0/s3_bucket_name-cAiL75
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/predict-pipeline
              awslogs-region: eu-central-1
              awslogs-stream-prefix: ecs
