AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket to store Datasets and MLflow tracking

Resources:
  MlopsDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: athos-mlops0-bucket
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Bucket Name
    Value: !Ref MlopsDataBucket