site_name: MLOps Template

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ "src" ]

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - Configuration:
      - Project config: config.md

  - Notebooks: notebooks.md
