[tool.poetry]
name = "mlops_project"
version = "0.0.1"
description = "MLOPs Project 1 End to End"
authors = ["Athos <athos@gmail.com>"]
readme = "README.md"
packages = [{ include = "src/mlops_project" }]

[tool.poetry.dependencies]
python = "^3.12"
pandas = "*"
numpy = "*"
scikit-learn = "*"

[tool.poetry.group.dev.dependencies]
#add dev libs here (pytest, black...)

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
