project_name: concrete-strength-project

# General configuration
type: regression # classification or regression
target: CompressiveStrength
id_column:


# Data Source
data_source: 'csv_url' # csv_url, csv_s3 or mysql
csv_separator:

# Train
random_state: 42

