project_name: pima-diabetes-project

# General configuration
type: classification # classification or regression
target: diabetes
id_column: None


# Data Source
data_source: 'mysql' # csv_url, csv_s3 or mysql
csv_separator:   # if necessary, by default -> ","

# Train
random_state: 42

