project_name: titanic-classification

# Task configuration
type: classification
target: Survived
id_column: PassengerId
retrain_only: True # retrain existing model from s3

# Train/test split
random_state: 42

