project_name: concrete-strength-project

# Task configuration
type: regression # classification or regression
target: CompressiveStrength
id_column:
csv_separator:

# Train/test split
random_state: 42

