project_name: house-prices-prediction

# Task configuration
type: regression # classification or regression
target: median_house_value
id_column: None
retrain_only: True # retrain existing model from s3

# Train/test split
random_state: 42

