name: MLOps Pipeline

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  AWS_ACCOUNT_ID: 831926591468
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  ECR_TRAIN: train-pipeline
  ECR_PREDICT: predict-pipeline
  ECS_CLUSTER: mlops-cluster
  SUBNET_ID: subnet-0bf5fd796a3288a2e
  SECURITY_GROUP_ID: sg-003463c73aab777ed

jobs:

  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy S3
        run: |
          aws cloudformation deploy \
            --template-file infra/cloudformation/s3_bucket.yaml \
            --stack-name mlops-s3 \
            --parameter-overrides BucketName=${{ env.S3_BUCKET_NAME }} \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy ECR repos
        run: |
          aws cloudformation deploy \
            --template-file infra/cloudformation/ecr.yaml \
            --parameter-overrides \
              EcrTrain=${{ env.ECR_TRAIN }} \
              EcrPredict=${{ env.ECR_PREDICT }} \
            --stack-name mlops-ecr

      - name: Deploy ECS Cluster
        run: |
          aws cloudformation deploy \
            --template-file infra/cloudformation/ecs_cluster.yaml \
            --parameter-overrides ClusterName=${{ env.ECS_CLUSTER }} \
            --stack-name mlops-ecs-cluster

      - name: Deploy ECS Task Definitions
        run: |
          aws cloudformation deploy \
            --template-file infra/cloudformation/ecs_task.yaml \
            --stack-name mlops-task \
            --capabilities CAPABILITY_NAMED_IAM


  build-and-push:
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build and Push TRAIN image
        run: |
          docker build -f Dockerfile.train -t ${{ env.ECR_TRAIN }} .
          docker tag ${{ env.ECR_TRAIN }}:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_TRAIN }}:latest
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_TRAIN }}:latest

      - name: Build and Push PREDICT image
        run: |
          docker build -f Dockerfile.predict -t ${{ env.ECR_PREDICT }} .
          docker tag ${{ env.ECR_PREDICT }}:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_PREDICT }}:latest
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_PREDICT }}:latest


  run-train:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Run ECS train task
        run: |
          aws ecs run-task \
            --cluster ${{ env.ECS_CLUSTER }} \
            --launch-type FARGATE \
            --task-definition train-pipeline-task \
            --network-configuration "awsvpcConfiguration={subnets=[${{ env.SUBNET_ID }}],securityGroups=[${{ env.SECURITY_GROUP_ID }}],assignPublicIp=ENABLED}" \
            --count 1

  run-predict:
    runs-on: ubuntu-latest
    needs: run-train
    steps:
      - name: Run ECS predict task
        run: |
          aws ecs run-task \
            --cluster ${{ env.ECS_CLUSTER }} \
            --launch-type FARGATE \
            --task-definition predict-pipeline-task \
            --network-configuration "awsvpcConfiguration={subnets=[${{ env.SUBNET_ID }}],securityGroups=[${{ env.SECURITY_GROUP_ID }}],assignPublicIp=ENABLED}" \
            --count 1
