name: Predict - Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  CLUSTER_NAME: mlops-cluster
  TASK_DEFINITION: predict-pipeline-task
  SUBNET_ID: subnet-0bf5fd796a3288a2e
  SECURITY_GROUP_ID: sg-003463c73aab777ed

jobs:
  deploy-predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy ECS Task Definition (Predict)
        run: |
          echo "🚀 START - Predict ECS Task Definition Deployment"
          aws cloudformation deploy \
            --template-file infra/cloudformation/ecs_task.yaml \
            --stack-name mlops-task \
            --capabilities CAPABILITY_NAMED_IAM
          echo "✅ END - Predict ECS Task Definition Deployment"

      - name: Run ECS prediction task
        run: |
          echo "🚀 Running ECS Fargate prediction task..."
          aws ecs run-task \
            --cluster $CLUSTER_NAME \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID],securityGroups=[$SECURITY_GROUP_ID],assignPublicIp=ENABLED}" \
            --task-definition $TASK_DEFINITION \
            --count 1
