name: Reset S3 Bucket

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  cleanup-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Empty S3 bucket
        run: |
          echo "🧹 Deleting all objects in s3://${{ env.S3_BUCKET_NAME }}..."
          aws s3 rm s3://${{ env.S3_BUCKET_NAME }} --recursive
          echo "✅ Bucket emptied"
