name: Train - Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  CLUSTER_NAME: mlops-cluster
  TASK_DEFINITION: train-pipeline-task
  SUBNET_ID: subnet-0bf5fd796a3288a2e
  SECURITY_GROUP_ID: sg-003463c73aab777ed

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy S3 bucket (dev)
        run: |
          echo "🚀 START - S3 Bucket Deployment"
          aws cloudformation deploy \
            --parameter-overrides BucketName=$S3_BUCKET_NAME \
            --template-file infra/cloudformation/s3_bucket.yaml \
            --stack-name mlops-s3 \
            --capabilities CAPABILITY_NAMED_IAM
          echo "✅ END - S3 Bucket Deployment"

      - name: Deploy ECR repository
        run: |
          echo "🚀 START - ECR Repo Deployment"
          aws cloudformation deploy \
            --template-file infra/cloudformation/ecr.yaml \
            --stack-name mlops-ecr
          echo "✅ END - ECR Repo Deployment"

      - name: Deploy ECS Cluster
        run: |
          echo "🚀 START - ECS Cluster Deployment"
          aws cloudformation deploy \
            --template-file infra/cloudformation/ecs_cluster.yaml \
            --stack-name mlops-ecs-cluster
          echo "✅ END - ECS Cluster Deployment"

      - name: Deploy ECS Task Definition
        run: |
          echo "🚀 START - ECS Task Definition Deployment"
          aws cloudformation deploy \
            --template-file infra/cloudformation/ecs_task.yaml \
            --stack-name mlops-task \
            --capabilities CAPABILITY_NAMED_IAM
          echo "✅ END - ECS Task Definition Deployment"

      - name: Run ECS training task
        run: |
          echo "🚀 Running ECS Fargate training task..."
          aws ecs run-task \
            --cluster $CLUSTER_NAME \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID],securityGroups=[$SECURITY_GROUP_ID],assignPublicIp=ENABLED}" \
            --task-definition $TASK_DEFINITION \
            --count 1

